### ISSUE TITLE
fanficfare not working with python 3.10

### ISSUE THREAD

**Issue by xzcvczx** [JimmXinu/FanFicFare#748]
when i updated the plugin a few days ago it stopped working

running in debug mode

```
File "calibre_plugins.fanficfare_plugin.fff_util", line 55, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

I modified the fff_util.py file to use collections.abc.MutableSet and it is now working again

collections.abc used to be collections in python 3.3 so depending on what versions of python you want to support it might require something for compatibility
