### ISSUE TITLE
Getting errors after updating to 4.50.0

### ISSUE THREAD

**Issue by SammaelNex** [JimmXinu/FanFicFare#1273]
I updated to 4.50.0 today and now whenever I try to get a new fic downloaded from either AO3 or FF.Net using the browser cache method I get the following error:

NoneType' object has no attribute 'replace

It worked fine before the upgrade.
