### ISSUE TITLE
AttributeError: 'dict_keys' object has no attribute 'sort'

### ISSUE THREAD

**Issue by tartpvule** [JimmXinu/FanFicFare#400]
Example URL: https://forum.questionablequesting.com/threads/shinobi-the-rpg-act-2-naruto-fallout-si.9517/
It has an "Extras" threadmark group.
Fanficfare Version 3.8.0, running on Python 3.7

Error:
```
Traceback (most recent call last):
  File "<scrubbed>", line 11, in <module>
    load_entry_point('FanFicFare==3.8.0', 'console_scripts', 'fanficfare')()
  File "<scrubbed>/fanficfare/cli.py", line 290, in main
    passed_personalini)
  File "<scrubbed>/fanficfare/cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "<scrubbed>/fanficfare/adapters/base_adapter.py", line 287, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "<scrubbed>/fanficfare/adapters/base_adapter.py", line 371, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "<scrubbed>/fanficfare/adapters/base_xenforoforum_adapter.py", line 419, in extractChapterUrlsAndMetadata
    threadmarks = self.extract_threadmarks(souptag)
  File "<scrubbed>/fanficfare/adapters/base_xenforoforum_adapter.py", line 303, in extract_threadmarks
    cats.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

In https://docs.python.org/3/whatsnew/3.0.html, section "Views And Iterators Instead Of Lists"
`dict methods dict.keys(), dict.items() and dict.values() return “views” instead of lists. For example, this no longer works: k = d.keys(); k.sort(). Use k = sorted(d) instead (this works in Python 2.5 too and is just as efficient).`

**Comment by JimmXinu** [comment]
Test version of CLI for pip install:  You'll have to get it from the testpypi repository.  This works for me on Debian:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

Or pip3 depending on your install.
