### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'other'

### ISSUE THREAD

**Issue by kido5217** [JimmXinu/FanFicFare#661]
I'm getting tihs error after upgrading to 4.0.2.

Version:
```
kido@sparky ~/temp> fanficfare --version
Version: 4.0.2
```
Full error:
```
kido@sparky ~/temp> fanficfare "https://www.fanfiction.net/s/10742358/1/The-Darkest-Art"
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.0.2', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 297, in main
    do_download(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 336, in do_download
    configuration = get_configuration(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 618, in get_configuration
    options.cookiejar = configuration.get_cookiejar()
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 1027, in get_cookiejar
    return self.get_fetcher().get_cookiejar(filename)
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 984, in get_fetcher
    self.fetcher = fetchcls(self.getConfig,
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 472, in __init__
    super(CloudScraperFetcher,self).__init__(getConfig_fn,getConfigList_fn)
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 401, in __init__
    self.retries = self.make_retries()
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 410, in make_retries
    return Retry(total=4,
TypeError: __init__() got an unexpected keyword argument 'other'
```
Same error with other site:
```
kido@sparky ~/temp> fanficfare "https://forum.questionablequesting.com/threads/is-it-wrong-to-devour-monsters-in-the-dungeon-danmachi-insert.14137/"
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.0.2', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 297, in main
    do_download(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 336, in do_download
    configuration = get_configuration(url,
  File "/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 618, in get_configuration
    options.cookiejar = configuration.get_cookiejar()
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 1027, in get_cookiejar
    return self.get_fetcher().get_cookiejar(filename)
  File "/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 984, in get_fetcher
    self.fetcher = fetchcls(self.getConfig,
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 401, in __init__
    self.retries = self.make_retries()
  File "/usr/lib/python3.9/site-packages/fanficfare/fetcher.py", line 410, in make_retries
    return Retry(total=4,
TypeError: __init__() got an unexpected keyword argument 'other'
```

**Comment by JimmXinu** [comment]
What is your installed version of `urllib3`?  Does updating `urllib3` fix it?

I put a requirement for `'urllib3 >= 1.26.2'` in FFF CLI, but perhaps it didn't work, or I need a higher version yet.

**Comment by kido5217** [comment]
I've installed it via arch's AUR fanficfare-git package, so it uses system's python modules. It's a possibility that package maintainer haven't updated dependencies. That said, I do have fresh urllib3:
```
kido@sparky ~> pip list | grep urllib
urllib3                       1.26.3
```
Update:
I've done more digging and it seems that fresh install in venv works just fine. Any thoughts on what module I need to install or update in my system?
Feel free to close this issue though, as it seems like it's arch's AUR package issue.

**Comment by JimmXinu** [comment]
The error is about the [`other` parameter of the `Retry` class in `urllib3`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L96).  It's a relatively recent addition (April 2020) and was present in `urllib3` 1.26.2, so I set that as the minimum required version for FanFicFare.

I don't know anything about downstream packagers like AUR, sorry.

**Comment by kido5217** [comment]
I've reinstalled urllib3 package (python-urllib3 in arch's repo) and now fff works.
```
kido@sparky ~> sudo pacman -Rdd python-urllib3
kido@sparky ~> sudo pacman -S --asdeps python-urllib3
```
I don't know if it was something broken in my system, or some arch's packages problem, but now it's solved.
Thank you.

**Comment by JimmXinu** [comment]
Glad you got it sorted out.
