### ISSUE TITLE
AttributeError:'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by glenm125** [JimmXinu/FanFicFare#420]
After upgrade from 3.9.0 to 3.10.0, Get Story URLs from Email fails  with message above.
Below are details.
<pre><code>
calibre, version 3.46.0
ERROR: Unhandled exception: <b>AttributeError</b>:'NoneType' object has no attribute 'group'

calibre 3.46  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 10, 0) && Reading List (1, 6, 6)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 478, in get_urls_from_imap_menu
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 228, in get_urls_from_imap
AttributeError: 'NoneType' object has no attribute 'group'
</code?</pre>

**Comment by JimmXinu** [comment]
Please try the [posted test version](https://www.mobileread.com/forums/showthread.php?p=3084025#post3084025).

If it still fails, please run Calibre in debug mode (Calibre Preferences dropdown) and report the debug log.
